"use client";

import { useState } from "react";
import { AssetModal } from "@/components/asset-modal";
import { confirmRegistration, createAsset, listAssets, type ApiAsset } from "@/lib/api";
import { registerAssetOnWallet } from "@/lib/wallet-registration";
import { useEffect } from "react";

const startingAssets: ApiAsset[] = [{ id: "local-1", name: "B.Tech Certificate", issuer: "National Institute of Technology", type: "Certificate", status: "REGISTERED", hash: "9f86d081...c7d65", createdAt: "" }, { id: "local-2", name: "Frontend Engineer License", issuer: "Open Web Guild", type: "License", status: "PENDING_BLOCKCHAIN", hash: null, createdAt: "" }, { id: "local-3", name: "Academic Transcript", issuer: "National Institute of Technology", type: "Transcript", status: "REGISTERED", hash: "2c26b46b...b8b16", createdAt: "" }];

export default function AssetsPage() {
  const [assets, setAssets] = useState(startingAssets); const [modalOpen, setModalOpen] = useState(false); const [filter, setFilter] = useState("All"); const [apiError, setApiError] = useState(""); const [registering, setRegistering] = useState("");
  useEffect(() => { listAssets().then(setAssets).catch(() => setApiError("Showing local preview data. Start the API to sync your vault.")); }, []);
  function addAsset(name: string, type: string, file: File) { createAsset({ name, type, file }).then((asset) => { setAssets((current) => [asset, ...current]); setModalOpen(false); }).catch(() => setApiError("The asset could not be saved. Please check the API connection.")); }
  async function register(asset: ApiAsset) { if (!asset.hash) return; setRegistering(asset.id); setApiError(""); try { const transactionHash = await registerAssetOnWallet(asset.id, asset.hash); const confirmed = await confirmRegistration(asset.id, transactionHash); setAssets((current) => current.map((item) => item.id === asset.id ? confirmed : item)); } catch (error) { setApiError(error instanceof Error ? error.message : "Registration could not be completed."); } finally { setRegistering(""); } }
  const visible = filter === "All" ? assets : assets.filter((asset) => asset.status === (filter === "Registered" ? "REGISTERED" : "PENDING_BLOCKCHAIN"));
  return <div className="page-body"><div className="page-title"><div><p className="eyebrow">Your vault</p><h1>Digital assets</h1><p className="lede">Credentials you own, share, and verify.</p></div><button className="primary-button" onClick={() => setModalOpen(true)}><span>+</span> Add asset</button></div>{apiError && <div className="toast">! {apiError}</div>}<div className="filter-bar"><div className="segmented">{["All", "Registered", "Pending"].map((item) => <button className={filter === item ? "selected" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><span className="asset-count">{visible.length} assets</span></div><div className="asset-table"><div className="table-head"><span>Asset</span><span>Type</span><span>Status</span><span>Document hash</span><span /></div>{visible.map((asset) => <div className="table-row" key={asset.id}><div className="asset-main"><div className={`asset-symbol ${asset.status === "REGISTERED" ? "mint" : "amber"}`}>✦</div><div><h3>{asset.name}</h3><p>{asset.issuer}</p></div></div><span className="asset-type">{asset.type}</span><span className={`status-pill ${asset.status === "REGISTERED" ? "registered" : "pending"}`}><i />{asset.status === "REGISTERED" ? "Registered" : "Pending"}</span><code>{asset.hash ?? "Waiting for upload"}</code>{asset.status === "PENDING_BLOCKCHAIN" ? <button className="review-button" disabled={registering === asset.id} onClick={() => register(asset)}>{registering === asset.id ? "Waiting..." : "Register"}</button> : <button className="more-button" aria-label={`Open ${asset.name}`}>→</button>}</div>)}</div>{modalOpen && <AssetModal onClose={() => setModalOpen(false)} onCreated={addAsset} />}</div>;
}
