/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RaksaRegistry {
  export type AssetStruct = {
    documentHash: BytesLike;
    owner: AddressLike;
    issuer: AddressLike;
    createdAt: BigNumberish;
    revoked: boolean;
  };

  export type AssetStructOutput = [
    documentHash: string,
    owner: string,
    issuer: string,
    createdAt: bigint,
    revoked: boolean
  ] & {
    documentHash: string;
    owner: string;
    issuer: string;
    createdAt: bigint;
    revoked: boolean;
  };
}

export interface RaksaRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAccess"
      | "getAsset"
      | "grantAccess"
      | "registerAsset"
      | "revokeAccess"
      | "revokeAsset"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "AssetRegistered"
      | "AssetRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAsset",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAsset",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    recipient: AddressLike,
    permissionType: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    recipient: string,
    permissionType: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    assetId: string;
    recipient: string;
    permissionType: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [assetId: BytesLike, recipient: AddressLike];
  export type OutputTuple = [assetId: string, recipient: string];
  export interface OutputObject {
    assetId: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    documentHash: BytesLike,
    owner: AddressLike,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    assetId: string,
    documentHash: string,
    owner: string,
    issuer: string
  ];
  export interface OutputObject {
    assetId: string;
    documentHash: string;
    owner: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRevokedEvent {
  export type InputTuple = [assetId: BytesLike];
  export type OutputTuple = [assetId: string];
  export interface OutputObject {
    assetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RaksaRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RaksaRegistry;
  waitForDeployment(): Promise<this>;

  interface: RaksaRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAccess: TypedContractMethod<
    [
      assetId: BytesLike,
      recipient: AddressLike,
      requiredPermission: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getAsset: TypedContractMethod<
    [assetId: BytesLike],
    [RaksaRegistry.AssetStructOutput],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [
      assetId: BytesLike,
      recipient: AddressLike,
      permissionType: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerAsset: TypedContractMethod<
    [assetId: BytesLike, documentHash: BytesLike, issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [assetId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAsset: TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      recipient: AddressLike,
      requiredPermission: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [RaksaRegistry.AssetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      recipient: AddressLike,
      permissionType: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [assetId: BytesLike, documentHash: BytesLike, issuer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [assetId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAsset"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AssetRevoked"
  ): TypedContractEvent<
    AssetRevokedEvent.InputTuple,
    AssetRevokedEvent.OutputTuple,
    AssetRevokedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(bytes32,address,uint8,uint64)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(bytes32,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "AssetRegistered(bytes32,bytes32,address,address)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "AssetRevoked(bytes32)": TypedContractEvent<
      AssetRevokedEvent.InputTuple,
      AssetRevokedEvent.OutputTuple,
      AssetRevokedEvent.OutputObject
    >;
    AssetRevoked: TypedContractEvent<
      AssetRevokedEvent.InputTuple,
      AssetRevokedEvent.OutputTuple,
      AssetRevokedEvent.OutputObject
    >;
  };
}
