"use client";

import { useState } from "react";

const initialRequests = [{ organization: "Open Web Guild", initials: "OW", action: "verify", asset: "Frontend Engineer License", tone: "" }, { organization: "NIT Registrar", initials: "NT", action: "view", asset: "Academic Transcript", tone: "coral" }];

export default function AccessPage() {
  const [requests, setRequests] = useState(initialRequests); const [notice, setNotice] = useState("");
  function respond(organization: string, accepted: boolean) { setRequests((current) => current.filter((request) => request.organization !== organization)); setNotice(`${organization} request ${accepted ? "approved" : "declined"}.`); }
  return <div className="page-body"><div className="page-title"><div><p className="eyebrow">Owner controls</p><h1>Access & permissions</h1><p className="lede">You stay in control of who can use your credentials.</p></div></div>{notice && <div className="toast" role="status">✓ {notice}</div>}<div className="access-summary"><div><span className="metric-label">Active permissions</span><strong>03</strong></div><div><span className="metric-label">Pending requests</span><strong>{String(requests.length).padStart(2, "0")}</strong></div><div><span className="metric-label">Expiring soon</span><strong>01</strong></div></div><section className="access-section"><div className="section-heading"><div><p className="eyebrow">Needs attention</p><h2>Incoming requests</h2></div></div>{requests.length ? requests.map((request) => <article className="access-request" key={request.organization}><div className={`request-avatar ${request.tone}`}>{request.initials}</div><div className="request-copy"><h3>{request.organization}</h3><p>Requests permission to <strong>{request.action}</strong> <b>{request.asset}</b></p><small>Received today · expires in 7 days</small></div><div className="request-actions"><button className="approve-button" onClick={() => respond(request.organization, true)}>Approve</button><button className="decline-button" onClick={() => respond(request.organization, false)}>Decline</button></div></article>) : <div className="empty-state"><span>✓</span><strong>You&apos;re all caught up</strong><p>There are no pending access requests.</p></div>}</section><section className="access-section"><div className="section-heading"><div><p className="eyebrow">Currently shared</p><h2>Active permissions</h2></div></div><div className="permission-row"><div className="request-avatar">OW</div><div className="request-copy"><h3>Open Web Guild</h3><p>Can verify <b>Frontend Engineer License</b></p></div><span className="permission-status">Active · 30 days</span><button className="revoke-button">Revoke</button></div><div className="permission-row"><div className="request-avatar coral">NT</div><div className="request-copy"><h3>NIT Registrar</h3><p>Can view <b>Academic Transcript</b></p></div><span className="permission-status">Active · 6 months</span><button className="revoke-button">Revoke</button></div></section></div>;
}
